### ISSUE TITLE
Python error at execution

### ISSUE THREAD

**Issue by Hyooni** [orf/xcat#15]
Hello everyone, 

I'm currently testing xCat for research purpose, and I can't seem to make it work.
When I launch xCat after installation, I get a lot of Python error about methods not an attribute of object "module" (see log attached).

For the installation process, I've installed it with `pip3 install xcat`.
My version of Python is 
`root@xxx:~/Téléchargements# python3.4 -V`
`Python 3.4`
And OS is 
`root@xxx:~/Téléchargements# uname -r`
`4.3.0-kali1-amd64
`
UPDATE : Also, the problem have repeated itself while using a Debian 3.16.0-4

Anyone got this problem too ? Or know how to solve it ?

Thanks in advance for the help, let me know if further information is needed :)

Hyooni

[xcat.log.zip](https://github.com/orf/xcat/files/830128/xcat.log.zip)

**Comment by orf** [comment]
Ahh, it seems master is broken (one of the dependencies has been updated but the code has not). I have made a new version of XCat that works with Python 3.6 and above, but it is not merged into master or released. I aim to do this soon.

**Comment by orf** [comment]
Closing in favor of #16
