### ISSUE TITLE
xcat-3.6-redesign-wtf prompt_toolkit issues

### ISSUE THREAD

**Issue by dale-paul** [orf/xcat#22]
The latest version of xcat does not work with prompt_toolkit==2.0.2.
Had to roll it back to 1.0.9 manually to get the build to work. Recommend putting this version in your dependency list

**Comment by lzskyline** [comment]
I have tried to modify the code, have a try.

**Comment by vratiskol** [comment]
Temporary bypass to roll back: 

`pip install -e git+https://github.com/jonathanslenders/python-prompt-toolkit@1.0.15#egg=prompt_toolkit`

@lzskyline: Try with last version with no luck

**Comment by orf** [comment]
I'm aware of this and I'm working on it. I've redesigned the internals, current master is working-ish but still needs work (OOB and shell).

**Comment by orf** [comment]
Hello,
I've just released `xcat` 1.0 on pypi 🎉 . I've redesigned the CLI and it now all works. Please see the updated README for information.

I'm working on the documentation now. Please open an issue if you run into trouble.
