### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Nixiabing** [orf/xcat#27]
Could not find a version that satisfies the requirement ipgetter (from xcat==0.9) (from versions: )
No matching distribution found for ipgetter (from xcat==0.9)

python=3.6.3

**Comment by Nixiabing** [comment]
<img width="570" alt="wx20181130-160354 2x" src="https://user-images.githubusercontent.com/20591728/49276466-98885a00-f4b9-11e8-91ef-236132bf748f.png">

**Comment by orf** [comment]
I'm aware of this and I'm working on it. I've redesigned the internals, current master is working-ish but still needs work (OOB and shell).

**Comment by orf** [comment]
Hello,
I've just released `xcat` 1.0 on pypi 🎉 . I've redesigned the CLI and it now all works. Please see the updated README for information.

I'm working on the documentation now. Please open an issue if you run into trouble.
