### ISSUE TITLE
Unable to run xcat

### ISSUE THREAD

**Issue by pranavsivvam** [orf/xcat#34]
I am unable to run xcat after installing it using "_pip3 install xcat_" . 
OS: Kali 5.2.0 (2019)
Python version: 3.7.4
The module in the error is also present in my system. I have tried a lot but am unable to run xcat.

![Screenshot from 2019-12-30 07-04-26](https://user-images.githubusercontent.com/37404408/71581325-a3555a00-2ad2-11ea-9242-f1d7ab0a4ecc.png)

**Comment by aram1s21** [comment]
Same for me. I solve the issue by downgrading the version. Not a solution but a workaround.
pip3 uninstall prompt_toolkit
pip3 install -Iv 'prompt_toolkit==2.0.10'

**Comment by orf** [comment]
Hey! Sorry about the inaction on this. I've pushed a new release that should now work correctly.

**Comment by adamczi** [comment]
Hi @orf , I use Python 3.7.6, installed latest xcat with pip (1.0.5) and I get the same error.

**Comment by adamczi** [comment]
Ok, sorry, I guess it's fine - tested on a very fresh Kali (with Python 3.7.6)
