### ISSUE TITLE
When trying to PXE boot, node status is going into standingby state

### ISSUE THREAD

**Issue by Shubhangi-dell** [orf/xcat#43]
Hi,
I have a 3 node cluster. When trying to PXE boot the cluster with ubuntu, one of the node is showing boot status as standingby and all the other nodes are booting up properly.

The pxe booting screen is getting stuck at ,
![image](https://github.com/orf/xcat/assets/72869337/2700ef1e-594a-4371-a44f-6fe96c00175f)

Can someone please help as to when the nodes go into standingby mode?

**Comment by orf** [comment]
Always good to double check where you’re posting issues 👍
